// Generated by buildtools/audio/make_header.py with menu_music.mp3 beside it;
// buildtools/audio/README.md has the source, the licence and how to make them
// again. Do not edit.
#ifndef MENU_MUSIC_MP3_H
#define MENU_MUSIC_MP3_H

#define MENU_MUSIC_RATE        32000
#define MENU_MUSIC_FRAME_BYTES 432
#define MENU_MUSIC_LOOP_START  960785  // decoded samples, delay of 1105 included
#define MENU_MUSIC_LOOP_END    3671869
#define MENU_MUSIC_MP3_LEN     1389312  // 3216 frames; MAD_BUFFER_GUARD zeros follow

/* The stream, then MAD_BUFFER_GUARD zeros. One byte past its length is
 * asked for, so a file that is not exactly that long fails the assert. */
static const unsigned char menu_music_mp3[] = {
#embed "menu_music.mp3" limit(MENU_MUSIC_MP3_LEN + 1) suffix(, 0, 0, 0, 0, 0, 0, 0, 0)
};
_Static_assert(sizeof(menu_music_mp3) == MENU_MUSIC_MP3_LEN + 8,
	"menu_music.mp3 is not MENU_MUSIC_MP3_LEN bytes");

#endif
