// Generated by buildtools/audio/make_header.py; buildtools/audio/README.md has
// the source, the licence and how to make it again. Do not edit.
#ifndef MENU_MUSIC_MP3_H
#define MENU_MUSIC_MP3_H

#define MENU_MUSIC_RATE        32000
#define MENU_MUSIC_FRAME_BYTES 432
#define MENU_MUSIC_LOOP_START  960785  // decoded samples, delay of 1105 included
#define MENU_MUSIC_LOOP_END    3671869
#define MENU_MUSIC_MP3_LEN     1389312  // 3216 frames
#define MENU_MUSIC_MP3_CRC32   0x70C46B1Eu
// buildtools/audio/menu-music.mp3, which the zip puts here on the card
#define MENU_MUSIC_MP3_PATH    "swiss/indigo/menu-music.mp3"

#endif
