#!/usr/bin/env python3
"""Encode the menu music and write cube/swiss/source/gui/menu_music.mp3 and
menu_music_mp3.h, which embeds it.

The console streams the MP3 (gui/menuaudio.c) and loops it by seeking to an
MP3 frame, so the stream must be constant bitrate with every frame the same
size and no tag or Xing frame in front. Loop points are counted in decoded
samples from the start of the stream: the encoder's and decoder's delay
(1105 samples for LAME and libmad) is measured, not assumed.

usage: make_header.py mix.wav mix.wav.json [header]   (needs ffmpeg with libmp3lame)
"""
import json
import subprocess
import sys
from pathlib import Path

import numpy as np

RATE = 32000
KBPS = 96
FRAME_SAMPLES = 1152
FRAME_BYTES = 144 * KBPS * 1000 // RATE  # 432: exact at 32 kHz, so no padding
GUARD = 8  # libmad's MAD_BUFFER_GUARD


def frames(mp3: bytes) -> list[int]:
    """Every frame's size; refuses anything but MPEG-1 Layer III, 32 kHz, 96 kbps, unpadded."""
    sizes, at = [], 0
    while at < len(mp3):
        h = int.from_bytes(mp3[at:at + 4], "big")
        if (h >> 21) & 0x7FF != 0x7FF or (h >> 19) & 3 != 3 or (h >> 17) & 3 != 1:
            raise SystemExit(f"make_header: no MPEG-1 Layer III frame at byte {at}")
        if (h >> 12) & 15 != 7 or (h >> 10) & 3 != 2 or (h >> 9) & 1:
            raise SystemExit(f"make_header: frame at byte {at} is not 96 kbps / 32 kHz / unpadded")
        sizes.append(FRAME_BYTES)
        at += FRAME_BYTES
    if at != len(mp3):
        raise SystemExit("make_header: the stream does not end on a frame")
    return sizes


def decoder_delay(wav: Path, mp3: Path) -> int:
    def pcm(args: list[str]) -> np.ndarray:
        raw = subprocess.run(["ffmpeg", "-loglevel", "error", *args, "-f", "s16le", "-ac", "1", "-"],
                             check=True, capture_output=True).stdout
        return np.frombuffer(raw, "<i2").astype(float)
    src = pcm(["-i", str(wav)])
    dec = pcm(["-i", str(mp3)])  # no Xing/LAME tag: ffmpeg cannot trim, like libmad
    a = src[RATE * 40:RATE * 42]
    scores = [float(a @ dec[RATE * 40 + d:RATE * 42 + d]) for d in range(4000)]
    return int(np.argmax(scores))


def main() -> int:
    wav, meta = Path(sys.argv[1]), json.loads(Path(sys.argv[2]).read_text())
    header = Path(sys.argv[3]) if len(sys.argv) > 3 else \
        Path(__file__).resolve().parents[2] / "cube/swiss/source/gui/menu_music_mp3.h"
    mp3 = wav.with_suffix(".mp3")
    subprocess.run(["ffmpeg", "-loglevel", "error", "-y", "-i", str(wav), "-c:a", "libmp3lame",
                    "-b:a", f"{KBPS}k", "-ar", str(RATE), "-write_xing", "0", "-id3v2_version", "0",
                    "-f", "mp3", str(mp3)], check=True)
    data = mp3.read_bytes()
    count = len(frames(data))
    delay = decoder_delay(wav, mp3)
    start, end = meta["loop_start"] + delay, meta["loop_end"] + delay
    if not 0 < start < end <= count * FRAME_SAMPLES:
        raise SystemExit(f"make_header: loop {start}..{end} does not fit {count} frames")
    header.with_name("menu_music.mp3").write_bytes(data)
    header.write_text(
        "// Generated by buildtools/audio/make_header.py with menu_music.mp3 beside it;\n"
        "// buildtools/audio/README.md has the source, the licence and how to make them\n"
        "// again. Do not edit.\n"
        "#ifndef MENU_MUSIC_MP3_H\n#define MENU_MUSIC_MP3_H\n\n"
        f"#define MENU_MUSIC_RATE        {RATE}\n"
        f"#define MENU_MUSIC_FRAME_BYTES {FRAME_BYTES}\n"
        f"#define MENU_MUSIC_LOOP_START  {start}  // decoded samples, delay of {delay} included\n"
        f"#define MENU_MUSIC_LOOP_END    {end}\n"
        f"#define MENU_MUSIC_MP3_LEN     {len(data)}  // {count} frames; MAD_BUFFER_GUARD zeros follow\n\n"
        "/* The stream, then MAD_BUFFER_GUARD zeros. One byte past its length is\n"
        " * asked for, so a file that is not exactly that long fails the assert. */\n"
        "static const unsigned char menu_music_mp3[] = {\n"
        "#embed \"menu_music.mp3\" limit(MENU_MUSIC_MP3_LEN + 1) suffix("
        + ", 0" * GUARD + ")\n};\n"
        f"_Static_assert(sizeof(menu_music_mp3) == MENU_MUSIC_MP3_LEN + {GUARD},\n"
        "\t\"menu_music.mp3 is not MENU_MUSIC_MP3_LEN bytes\");\n\n#endif\n")
    print(f"{header}: {len(data)} bytes, {count} frames, delay {delay}, loop {start}..{end}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
